name: education_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.4
  chewie: ^1.8.5
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  file_picker: ^8.1.7
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_storage: ^12.4.0
  firebase_ui_auth: ^1.16.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  get_thumbnail_video: ^0.7.3
  iconly: ^1.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.2.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  provider: ^6.1.2
  puppeteer: ^3.16.0
  shared_preferences: ^2.3.4
  smooth_page_indicator: ^1.2.0+3
  swipe_to: ^1.0.6
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  change_app_package_name: ^1.4.0
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.1
  firebase_storage_mocks: ^0.7.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.3.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/vectors/
    - assets/icons/
    - assets/images/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
